<<<<<<< HEAD
- http/https:
    protocal: https

- desired_caps_info:
    appPackage: com.langlib.ncee
    appActivity: com.langlib.ncee.ui.main.SplashActivity
=======
>>>>>>> b19b592fa75a5594ff02fb1acc97b8cf8d037095

