- common:
    globals:
        env: test
        platformName: Android
        Platform: Android
        appPackage: com.langlib.ncee
        appActivity: com.langlib.ncee.ui.main.SplashActivity
        appkey: xxxx
        appversion: '10003000'
        AppSecret: xxxx
        App: cee
        Host_test: xxxx
        Host_cus: xxxx
        loginUrl_test: https://xxxx
        loginProxy_test: xxxx
        loginUrl_cus: https://xxxx
        loginProxy_cus: xxxx
        Host: None
        loginUrl: None
        loginProxy: None
        User-Agent: okhttp/3.11.0

- vivox6:
    appium_url:
        url: http://127.0.0.1:4723/wd/hub
    account:
        uname: txxxx@t.com
        pwd: xxxx
        loginUrl_test: https://xxxx
        loginProxy_test: xxxx
        loginUrl_cus: https:xxxxxcom
        loginProxy_cus: xxxx.com
    desired_caps:
        platformName:
        platformVersion: '6.0.1'
        deviceName: 33xxxxx0
        udid: 3xxxx0
        appPackage:
        appActivity:
        unicodeKeyboard: True
        resetKeyboard: True
    headers:
        Platform:
        appkey:
        appversion:
        AppSecret:
        App:
        Host:
        Connection: Keep-Alive
        Accept-Encoding: gzip
        User-Agent:
        accesstoken:
